import Image from 'next/image'

import { site } from '@/data/site'
import { cn } from '@/lib/utils'

export function BrandLogo({
  className,
  width = 236,
  priority = false,
  tone = 'brand',
}: {
  className?: string
  width?: number
  priority?: boolean
  /**
   * `light` is the brand's own cream lockup for navy surfaces, generated by
   * scripts/generate-logo-light.mjs — not a filtered version of the dark one.
   */
  tone?: 'brand' | 'light'
}) {
  return (
    <Image
      src={tone === 'light' ? '/assets/logo-light.svg' : '/assets/logo.svg'}
      alt={`${site.legalName} logo`}
      width={width}
      height={Math.round((width * 530) / 1312)}
      priority={priority}
      className={cn('h-auto', className)}
    />
  )
}
